// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeKAdE-V3ier7D-ZVvGaWMT5M3IzvGWnE',
    appId: '1:858324195483:web:cf9138c7e63aba03944e3e',
    messagingSenderId: '858324195483',
    projectId: 'sistemaevaluaciondocente',
    authDomain: 'sistemaevaluaciondocente.firebaseapp.com',
    storageBucket: 'sistemaevaluaciondocente.firebasestorage.app',
    measurementId: 'G-R41Y7PV9PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-Gi5nkovsUiKs6XY07xoDXIRYU3Z8LQ',
    appId: '1:858324195483:android:fc24625f16d958cb944e3e',
    messagingSenderId: '858324195483',
    projectId: 'sistemaevaluaciondocente',
    storageBucket: 'sistemaevaluaciondocente.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPMmMKiiFFbBsRP2kzOxU6dRo4TqYeQqM',
    appId: '1:858324195483:ios:ebd4322daa4374a9944e3e',
    messagingSenderId: '858324195483',
    projectId: 'sistemaevaluaciondocente',
    storageBucket: 'sistemaevaluaciondocente.firebasestorage.app',
    iosBundleId: 'com.example.sistemaEvaluacionUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPMmMKiiFFbBsRP2kzOxU6dRo4TqYeQqM',
    appId: '1:858324195483:ios:ebd4322daa4374a9944e3e',
    messagingSenderId: '858324195483',
    projectId: 'sistemaevaluaciondocente',
    storageBucket: 'sistemaevaluaciondocente.firebasestorage.app',
    iosBundleId: 'com.example.sistemaEvaluacionUts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeKAdE-V3ier7D-ZVvGaWMT5M3IzvGWnE',
    appId: '1:858324195483:web:316fac7f9c5ef32c944e3e',
    messagingSenderId: '858324195483',
    projectId: 'sistemaevaluaciondocente',
    authDomain: 'sistemaevaluaciondocente.firebaseapp.com',
    storageBucket: 'sistemaevaluaciondocente.firebasestorage.app',
    measurementId: 'G-W9CE2THGJ1',
  );
}
